CREATE DATABASE IF NOT EXISTS telemeal;
USE telemeal;
CREATE TABLE IF NOT EXISTS favorites (
    idMeal INT AUTO_INCREMENT PRIMARY KEY,  
    strMeal VARCHAR(255),                     
    strCategory VARCHAR(255),                   
    strArea VARCHAR(255),                     
    strInstructions TEXT,                  
    strMealThumb VARCHAR(255),                  
    strYoutube VARCHAR(255),                
    strSource VARCHAR(255),                     
    strTags VARCHAR(255),                       
    strIngredient1 VARCHAR(255),          
    strIngredient2 VARCHAR(255),           
    strIngredient3 VARCHAR(255),                
    strIngredient4 VARCHAR(255),                
    strIngredient5 VARCHAR(255),               
    strIngredient6 VARCHAR(255),                
    strIngredient7 VARCHAR(255),             
    strIngredient8 VARCHAR(255),              
    strIngredient9 VARCHAR(255),                
    strIngredient10 VARCHAR(255),              
    strIngredient11 VARCHAR(255),          
    strMeasure1 VARCHAR(255),                 
    strMeasure2 VARCHAR(255),                  
    strMeasure3 VARCHAR(255),                  
    strMeasure4 VARCHAR(255),                  
    strMeasure5 VARCHAR(255),                  
    strMeasure6 VARCHAR(255),                 
    strMeasure7 VARCHAR(255),                  
    strMeasure8 VARCHAR(255),                   
    strMeasure9 VARCHAR(255),                  
    strMeasure10 VARCHAR(255),                  
    strMeasure11 VARCHAR(255)                 
);
